include:
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/general.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/test/test.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/test/lint.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/test/security.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/build/dist.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/build/docker.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/deploy/pages.yml
    - project: "AlekSIS/official/AlekSIS"
      file: /ci/deploy/pypi.yml
