# Generated by Django 3.1.5 on 2021-01-23 20:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_invitations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personinvitation',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='E-Mail'),
        ),
    ]
